name: nba
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - polars
  - duckdb
  - numpy
  - matplotlib
  - seaborn
  - sqlite
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - kaggle
      - pre-commit
      - click
